### ISSUE TITLE
OKhttp3 版本跟 springboot2.5.2的版本有冲突

### ISSUE THREAD

**Issue by edwardlau** [doocs/qcloud-im-server-sdk-java#103]
springboot 默认使用 okhttp3 3.14.9  本 jar 使用 4.9.3 使用时候会出现找不到对应方法。

<img width="847" alt="image" src="https://user-images.githubusercontent.com/2252194/162104847-f7368cd3-4f45-4b4c-9ba7-a823ec41bf07.png">

**Comment by yanglbme** [comment]
SpringBoot 里的依赖，将 okhttp 排除试试？

```xml
<exclusions>
    <exclusion>
        <groupId>com.squareup.okhttp3</groupId>
        <artifactId>okhttp</artifactId>
    </exclusion>
</exclusions>
```

**Comment by edwardlau** [comment]
@yamyamyuo

**Comment by edwardlau** [comment]
@yanglbme

**Comment by huangjunfa1** [comment]
同样遇到这个问题
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>okhttp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        
![image](https://user-images.githubusercontent.com/30465052/162105819-d7a028f0-f392-45ce-8c20-75033c7e95ec.png)

**Comment by huangjunfa1** [comment]
同样遇到这个问题。
![image](https://user-images.githubusercontent.com/30465052/162106090-4b0e9641-4603-4d60-bfd6-5578cd8a8d77.png)

**Comment by yanglbme** [comment]
看看是哪些 dependency 依赖了 okhttp3，把他们排除一下，依赖的查找可以用 IDEA 的 Dependency Analyzer，找到低版本的 okhttp，右键 exclude

**Comment by yanglbme** [comment]
可以参考一下这个，你们可以根据项目的实际情况排除冲突的依赖

```xml
<dependency>
    <groupId>com.tencentcloudapi</groupId>
    <artifactId>tencentcloud-sdk-java</artifactId>
    <version>3.1.423</version>
    <exclusions>
        <exclusion>
            <groupId>com.squareup.okio</groupId>
            <artifactId>okio</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
  <groupId>com.qiniu</groupId>
  <artifactId>qiniu-java-sdk</artifactId>
  <version>7.2.23</version>
  <exclusions>
      <exclusion>
          <groupId>com.squareup.okhttp3</groupId>
          <artifactId>okhttp</artifactId>
      </exclusion>
  </exclusions>
</dependency>
```

**Comment by edwardlau** [comment]
已解决，发现是版本管理问题，我们用了spring-boot-dependencies这个管理默认是 3.14.9，我把 4.9.3的贴过去就好了

**Comment by yanglbme** [comment]
好的

**Comment by CoolBlackJF** [comment]
简单处理方式： 
Spring 限制了 okhttp3 的版本，导致该sdk内的okhttps3版本失效。
