### ISSUE TITLE
Maven中央仓库SendGroupMsgRequest类缺少toAccount属性 

### ISSUE THREAD

**Issue by jetwu** [doocs/qcloud-im-server-sdk-java#106]
你好  
Maven中央仓库SendGroupMsgRequest类缺少toAccount属性  希望能更新下  谢谢

**Comment by yanglbme** [comment]
v0.3.16 已发布，预计这两天内能在 maven 仓库拉到最新版本，此版本补全了 toAccount 属性 @jetwu
