### ISSUE TITLE
生成请求url的时候，能否手动设置random

### ISSUE THREAD

**Issue by cmazxiaoma** [doocs/qcloud-im-server-sdk-java#126]
![image](https://user-images.githubusercontent.com/26736167/181205210-d5bdce02-92ae-4c21-85c0-df54f66e71c0.png)

因为调restapi，可能会出现各种问题。和腾讯相关的开发人员排查问题的时候，需要通过请求url的random进行定位问题

**Comment by yanglbme** [comment]
是说这里生成的 random 值可能有问题，需要排查？

**Comment by cmazxiaoma** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yanglbme** [comment]
把邮箱自动回复关一下吧。。

**Comment by cmazxiaoma** [comment]
就是我想调用发送消息接口，打印完整的url，其中包括random，便于定位问题



---原始邮件---
发件人: "Yang ***@***.***&gt;
发送时间: 2022年7月27日(周三) 下午5:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [doocs/qcloud-im-server-sdk-java] 生成请求url的时候，能否手动设置random (Issue #126)




 
把邮箱自动回复关一下吧。。

**Comment by cmazxiaoma** [comment]
Random生成没问题，但是我想拿到这个random
，到时间调接口出现问题，提供这个random，腾讯那边的开发可以定位问题。。。。



---原始邮件---
发件人: "Yang ***@***.***&gt;
发送时间: 2022年7月27日(周三) 下午5:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [doocs/qcloud-im-server-sdk-java] 生成请求url的时候，能否手动设置random (Issue #126)




 
是说这里生成的 random 值可能有问题，需要排查？

**Comment by yanglbme** [comment]
你可以写一下期望的使用方式，用代码片段表示出来。我们这边看一下 @cmazxiaoma

**Comment by cmazxiaoma** [comment]
![image](https://user-images.githubusercontent.com/26736167/181405238-735b75ba-0266-45cd-b3d7-11db70d7f855.png)

![image](https://user-images.githubusercontent.com/26736167/181405270-d79bf9c9-352e-4afa-b520-f94b1ba35467.png)

![image](https://user-images.githubusercontent.com/26736167/181405295-ef19903e-6dcc-4fbd-b45f-19014d22f46a.png)

**Comment by cmazxiaoma** [comment]
getUrl方法，增加一个入参就行

**Comment by yanglbme** [comment]
目前 request 是作为请求体来传输，将 url 里的 random 参数放这里不太合适

**Comment by cmazxiaoma** [comment]
那你觉得放在哪里，比较好？ 如果不放在GenericRequest里面，那加个random字段对代码侵入还是比较大的

**Comment by cmazxiaoma** [comment]
![image](https://user-images.githubusercontent.com/26736167/181437480-968d6d4c-912d-4cd9-9ac0-8cc6b0860647.png)
如果要代码规范的话，只能每个方法加个random参数了，上述是腾讯tencentcloud-im-sdk-java的实现

**Comment by yanglbme** [comment]
可以，我们在方法上加个 random 参数

**Comment by cmazxiaoma** [comment]
好的，谢谢大佬。。。。

**Comment by yanglbme** [comment]
v0.3.27 支持传入 random，这个 issue 我先关闭了哈。有其他的问题可以随时反馈
