### ISSUE TITLE
在设置超时时间的时候，默认都是3s,我上游调用的时候，应该设置多少s才能保证这里sdk一个请求响应已经结束，9s?

### ISSUE THREAD

**Issue by mufeng567** [doocs/qcloud-im-server-sdk-java#127]
`
public class ClientConfiguration {
    /**
     * 默认 UA
     */
    public static final String DEFAULT_USER_AGENT = VersionInfoUtil.getDefaultUserAgent();

    /**
     * 默认最大重试次数
     */
    public static final int DEFAULT_MAX_RETRIES = 3;

    /**
     * 默认自动更新签名
     */
    public static final boolean DEFAULT_RENEW_SIG = true;
    /**
     * 默认超时时间（毫秒）
     */
    public static final long DEFAULT_CONNECT_TIMEOUT = 3000L;
    public static final long DEFAULT_READ_TIMEOUT = 3000L;
    public static final long DEFAULT_WRITE_TIMEOUT = 3000L;、
...
//其他code
`

**Comment by yanglbme** [comment]
@mufeng567 

下个版本会新增一个 `callTimeout` 参数，用于控制一次完整的 http 调用的超时时间。

**Comment by yanglbme** [comment]
从 v0.3.25 开始，支持自定义 callTimeout
