### ISSUE TITLE
获取群组消息的时候，返回的next超出int最大值报错

### ISSUE THREAD

**Issue by yayanan** [doocs/qcloud-im-server-sdk-java#130]
`Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Numeric value (9040992949) out of range of int (-2147483648 - 2147483647)
`
这是源代码
public static void init() throws IOException {
        long appId = xxxxxxx;
        String userId = "xxxxxxxxxx";
        String key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
        ClientConfiguration config = new ClientConfiguration();
        config.setExpireTime(7 * 24 * 60 * 60L);
        config.setAutoRenewSig(false);
        ImClient client = ImClient.getInstance(appId, userId, key, config);
        GetAppIdGroupListRequest request = GetAppIdGroupListRequest.builder()
                .limit(50)
                .groupType(GroupType.PUBLIC)
                .next(0)
                .build();
        GetAppIdGroupListResult result = client.group.getAppIdGroupList(request);
        System.out.println(request);
    }

**Comment by yanglbme** [comment]
感谢反馈，我们待会修复后，发个新版本

**Comment by yanglbme** [comment]
v0.3.26 修复了此问题，请求参数、响应参数均为 long 型

**Comment by yayanan** [comment]
感谢修复，速度真快！
