### ISSUE TITLE
创建群组问题

### ISSUE THREAD

**Issue by gchzz** [doocs/qcloud-im-server-sdk-java#142]
创建群组时，如果定义了群组自定义字段对象且赋值，im会返回{groupId='null', actionStatus='FAIL', errorInfo='all defined key is invalid', errorCode=10004}参数无效。如果不传自定义字段或者只定义自定义字段对象不赋值则没有问题。将源码的AppDefinedDataItem key字段和value字段改为Key和Value也没有问题。
![image](https://user-images.githubusercontent.com/87818948/189337534-d688fa36-9477-46ce-82f7-fe3cadb1807f.png)
![image](https://user-images.githubusercontent.com/87818948/189337626-1aac3a25-5a39-4801-ba0d-04a735f9e4b4.png)

**Comment by yanglbme** [comment]
有没有在控制台配置？

![image](https://user-images.githubusercontent.com/21008209/189339458-3b84e51e-bbfa-405f-a6e1-4930e5377c7d.png)

**Comment by gchzz** [comment]
> 有没有在控制台配置？
> 
> ![image](https://user-images.githubusercontent.com/21008209/189339458-3b84e51e-bbfa-405f-a6e1-4930e5377c7d.png)

应该是没有，假期来了让运维配一下试试

**Comment by gchzz** [comment]
> 有没有在控制台配置？
> 
> ![image](https://user-images.githubusercontent.com/21008209/189339458-3b84e51e-bbfa-405f-a6e1-4930e5377c7d.png)

应该是没配置的原因，假期来了让运维配置后试一下。改成大写也会报错，之前对了应该是缓存。

**Comment by yanglbme** [comment]
好的，有问题随时反馈

**Comment by yanglbme** [comment]
这个 issue，我先关闭哈，如果有其他问题，可以继续提
