### ISSUE TITLE
update IM_BIRTHDAY tencent need int but give a string

### ISSUE THREAD

**Issue by Asa-Dong** [doocs/qcloud-im-server-sdk-java#146]
// tencent doc
Tag_Profile_IM_BirthDay | uint32 | 生日 | 有 | 推荐用法：20190419

// code
profiles.add(ProfileItem.builder().tag(TagProfile.IM_BIRTHDAY).value(birth).build());

tks for your work.
best wishes.

**Comment by yanglbme** [comment]
谢谢反馈，v0.3.32 版本发布了，过两天可以在 maven 仓库找到。新版本 TagProfile value 类型改为 Object
