### ISSUE TITLE
回调 实体类 字段缺失问题.

### ISSUE THREAD

**Issue by Antenbabby** [doocs/qcloud-im-server-sdk-java#160]
![image](https://user-images.githubusercontent.com/18116874/234827288-63d81f4a-3cf0-4ae8-95fa-ba9c0f9e3545.png)
回调实体类中部分字段缺失.

**Comment by yanglbme** [comment]
已修改，预计 v.0.3.40 版本会新增这些字段

**Comment by yanglbme** [comment]
v0.3.41 已发布，预计这两天能在 maven 中央仓库找到
