### ISSUE TITLE
SendGroupMsgResult 实体映射错误

### ISSUE THREAD

**Issue by syzpig** [doocs/qcloud-im-server-sdk-java#164]
@com.fasterxml.jackson.annotation.JsonProperty("MsgTime")
    private java.lang.Integer msgTime;
    @com.fasterxml.jackson.annotation.JsonProperty("msgSeq")
    private java.lang.Long msgSeq;
中msgSeq为应该为MsgSeq

**Comment by syzpig** [comment]
您好，可以在0.3.17 这个版本上修复嘛，我们升级发现会有一些方法不适用。怕影响历史功能。


还有方便加一个修改群历史记录的功能吗？我们有这个方面需求




流光飞尽泪无痕
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "doocs/qcloud-im-server-sdk-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 晚上9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [doocs/qcloud-im-server-sdk-java] SendGroupMsgResult 实体映射错误 (Issue #164)





 
感谢反馈，今天会发版修复此问题

**Comment by syzpig** [comment]
目前升级api改动会比较大，而且线上也会影响，就是时间来不及。所以想希望能够在这个包上修复。试了下，好多类和属性名变更，新版和老版本只是新增一些接口还有更改属性名嘛。




流光飞尽泪无痕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doocs/qcloud-im-server-sdk-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 晚上9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [doocs/qcloud-im-server-sdk-java] SendGroupMsgResult 实体映射错误 (Issue #164)





 
较低的版本可能会有别的问题，比如少了一些api，最好升到最新版

**Comment by syzpig** [comment]
目前升级api改动会比较大，而且线上也会影响，就是时间来不及。所以想希望能够在这个包上修复。试了下，好多类和属性名变更，新版和老版本只是新增一些接口还有更改属性名嘛。




流光飞尽泪无痕
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "doocs/qcloud-im-server-sdk-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 晚上9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [doocs/qcloud-im-server-sdk-java] SendGroupMsgResult 实体映射错误 (Issue #164)





 
较低的版本可能会有别的问题，比如少了一些api，最好升到最新版

**Comment by syzpig** [comment]
您好，那就历史版本不需要了，因为需要新功能，所以麻烦您了，非常感谢，我们使用最新包，我们改下相关功能。麻烦帮忙打个包，我们拉下最新代码看看，刚试了，最新44版本包没拉到。




流光飞尽泪无痕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doocs/qcloud-im-server-sdk-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [doocs/qcloud-im-server-sdk-java] SendGroupMsgResult 实体映射错误 (Issue #164)





 
最新的版本我先修复了
 
你可以看下在哪个版本上修复 msgSeq 比较合适，因为 v0.3.24 开始就新增了修改群历史相关的 api，而你目前使用的是 v0.3.17

**Comment by yanglbme** [comment]
最新的 44 版本已经发布，不过 maven 差不多要明天才能拉取到

**Comment by syzpig** [comment]
您好，打扰一下，咨询下，我看maven仓库还没有44版本，请问这个大概需要多久？是需要审核的嘛？应该不会很慢吧




流光飞尽泪无痕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doocs/qcloud-im-server-sdk-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 晚上10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [doocs/qcloud-im-server-sdk-java] SendGroupMsgResult 实体映射错误 (Issue #164)





 
最新的 44 版本已经发布，不过 maven 差不多要明天才能拉取到

**Comment by yanglbme** [comment]
maven 中央仓库有了的，你可以看看 https://central.sonatype.com/artifact/io.github.doocs/im-server-sdk-java/0.3.44

**Comment by syzpig** [comment]
嗯嗯，
这里面我看还没有，我们从maven mvnrepository这里面拉的，https://mvnrepository.com/artifact/io.github.doocs/im-server-sdk-java&nbsp;&nbsp;




流光飞尽泪无痕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doocs/qcloud-im-server-sdk-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月26日(星期三) 上午9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [doocs/qcloud-im-server-sdk-java] SendGroupMsgResult 实体映射错误 (Issue #164)





 
maven 中央仓库有了的，你可以看看 https://central.sonatype.com/artifact/io.github.doocs/im-server-sdk-java/0.3.44

**Comment by yanglbme** [comment]
pom.xml 直接引入这个

```xml
<dependency>
            <groupId>io.github.doocs</groupId>
            <artifactId>im-server-sdk-java</artifactId>
            <version>0.3.44</version>
        </dependency>
```

然后 reload 试试，我本地能拉到 0.3.44

**Comment by syzpig** [comment]
您好，可以了，非常感谢您的支持，我们有技术沟通群嘛，向我们多学习。
&nbsp;


流光飞尽泪无痕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yang ***@***.***&gt;; 
发送时间: 2023年7月26日(星期三) 上午9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [doocs/qcloud-im-server-sdk-java] SendGroupMsgResult 实体映射错误 (Issue #164)





 
pom.xml 直接引入这个
 <dependency&gt;             <groupId&gt;io.github.doocs</groupId&gt;             <artifactId&gt;im-server-sdk-java</artifactId&gt;             <version&gt;0.3.44</version&gt;         </dependency&gt;
 
然后 reload 试试，我本地能拉到 0.3.44

**Comment by syzpig** [comment]
您好，我们好像还是拉不到。能麻烦帮忙看下吗，您是不是本地包




流光飞尽泪无痕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doocs/qcloud-im-server-sdk-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月26日(星期三) 上午9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [doocs/qcloud-im-server-sdk-java] SendGroupMsgResult 实体映射错误 (Issue #164)





 
pom.xml 直接引入这个
 <dependency&gt;             <groupId&gt;io.github.doocs</groupId&gt;             <artifactId&gt;im-server-sdk-java</artifactId&gt;             <version&gt;0.3.44</version&gt;         </dependency&gt;
 
然后 reload 试试，我本地能拉到 0.3.44

**Comment by syzpig** [comment]
我看maven的的这个里面是没有的，https://mvnrepository.com/artifact/io.github.doocs/im-server-sdk-java，还是43版本的




流光飞尽泪无痕
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "doocs/qcloud-im-server-sdk-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月26日(星期三) 上午9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [doocs/qcloud-im-server-sdk-java] SendGroupMsgResult 实体映射错误 (Issue #164)





 
maven 中央仓库有了的，你可以看看 https://central.sonatype.com/artifact/io.github.doocs/im-server-sdk-java/0.3.44

**Comment by yanglbme** [comment]
不是本地包，你看看你的 maven 是不是配的阿里云镜像？阿里云镜像可能没那么快同步

**Comment by yanglbme** [comment]
看看还有没有问题，没有的话 issue 可以关闭
