### ISSUE TITLE
TIMMsgElement 这个类中缺少msgContent

### ISSUE THREAD

**Issue by SunZhihan1105** [doocs/qcloud-im-server-sdk-java#172]
如题，现在：
![Snipaste_2023-12-28_16-48-10](https://github.com/doocs/qcloud-im-server-sdk-java/assets/147681160/8f6484bc-6b3c-45c5-b630-2efa1b7f71fa)
官方文档：
![Snipaste_2023-12-28_16-48-26](https://github.com/doocs/qcloud-im-server-sdk-java/assets/147681160/77f062c3-4bad-4bc8-8af2-9ab0995545e7)

**Comment by yanglbme** [comment]
你截图的类是抽象父类，文本消息元素对应的类是：`TIMTextMsgElement`，继承自 `TIMMsgElement`

**Comment by SunZhihan1105** [comment]
好的 谢谢
