### ISSUE TITLE
一点疑问，望回复。

### ISSUE THREAD

**Issue by liqitian3344** [doocs/qcloud-im-server-sdk-java#179]
这个地方每次都要重新初始化okHttpClient，这块不会浪费资源嘛。（源码点进去格式奇怪 看不明白）
![image](https://github.com/doocs/qcloud-im-server-sdk-java/assets/29157770/e84df837-3d8b-4b23-933a-89594a195189)

**Comment by yanglbme** [comment]
写法上有问题，我们改一下
