### ISSUE TITLE
功能字段缺少

### ISSUE THREAD

**Issue by xiaomogu13tt** [doocs/qcloud-im-server-sdk-java#187]
0.4.06这个版本的修改群组资料少了几个字段，跟腾讯云的文档对不上，

![1726108244079](https://github.com/user-attachments/assets/84e4f0ab-68c0-4313-9e00-9a95491b83d4)

sdk的文档
![image](https://github.com/user-attachments/assets/c65f00b5-8c99-45b8-8fbe-9dd718237a32)
缺少最新的字段

**Comment by yanglbme** [comment]
你好，这些字段是官方新增的，我们在 v0.4.07 补充了这些新字段。

谢谢反馈 :)
