### ISSUE TITLE
需要新增离线推送字段OfflinePushInfo  AndroidInfo.HuaWeiCategory

### ISSUE THREAD

**Issue by lian1174** [doocs/qcloud-im-server-sdk-java#189]
需要新增离线推送字段OfflinePushInfo  AndroidInfo.HuaWeiCategory,需要消息分类新增字段AndroidInfo.HuaWeiCategory还有其他的遗漏字段。
腾讯的文档
https://cloud.tencent.com/document/product/269/2720#.E6.B6.88.E6.81.AF.E8.87.AA.E5.AE.9A.E4.B9.89.E6.95.B0.E6.8D.AE-cloudcustomdata-.E8.AF.B4.E6.98.8E

**Comment by yanglbme** [comment]
已处理，v0.4.08 版本新增这些字段
