### ISSUE TITLE
群聊拉取历史聊天记录消息体没有兼容系统消息

### ISSUE THREAD

**Issue by blank-date** [doocs/qcloud-im-server-sdk-java#190]
拉取群聊的聊天记录时，系统消息返回的不是数组，json反序列化时异常，看是否可以考虑兼容一下
![image](https://github.com/user-attachments/assets/da0508d4-aa40-40e6-ab16-3c8e6d3cc702)

**Comment by yanglbme** [comment]
可以的，我们兼容下

**Comment by yanglbme** [comment]
v0.4.09 兼容了不同类型的 msgBody

**Comment by blank-date** [comment]
点赞
