### ISSUE TITLE
get_specified_group_member_info  not found

### ISSUE THREAD

**Issue by cs13886** [doocs/qcloud-im-server-sdk-java#192]
Thanks for your shared.

i can't find  get_specified_group_member_info method from Group.

The doc url is  https://www.tencentcloud.com/zh/document/product/1047/64897.

Thanks.

**Comment by yanglbme** [comment]
Hello, thank you for the feedback. We have added the API in version v0.4.10. You can upgrade to this version to use it.

**Comment by cs13886** [comment]
So efficient, it's astonishing. Amazing!
