### ISSUE TITLE
UserSig 失效

### ISSUE THREAD

**Issue by YangYiYing** [doocs/qcloud-im-server-sdk-java#63]
[UserSig ](https://cloud.tencent.com/document/product/269/32688)

目前项目中设置过期时间为1天，且无自动刷新机制（io.github.doocs.im.ClientConfiguration）。
在服务器稳定运行一天后，会出现问题。

**Comment by yanglbme** [comment]
@YangYiYing 

每次调用时通过 `ImClient.getInstance()` 获取到一个 client 实例，是不会有签名过期问题的吧

**Comment by yanglbme** [comment]
我们考虑增加一个自动刷新机制

**Comment by yanglbme** [comment]
v0.2.9 默认对签名进行自动续期，同时支持用户自行配置
