### ISSUE TITLE
msgRandom类型问题

### ISSUE THREAD

**Issue by ZHOUZONGHAN** [doocs/qcloud-im-server-sdk-java#74]
官方文档中msgRandom属性接收是用int类型，SDK代码中用的是long，但是有一个数据范围[0,4294967295]的提示，为什么不直接使用Integer呢？是有什么特殊原因吗？

**Comment by yanglbme** [comment]
@ZHOUZONGHAN 

`[0,4294967295]` 的范围，实际上已经超过了 int 的最大值 2147483647，所以我们定义成 long

**Comment by ZHOUZONGHAN** [comment]
提一个建议哈  我觉得可以在msgRandom的set方法中加一个校验  或者直接使用Integer类型接收  毕竟只是用于同一秒内同一用户的消息去重  2147483647已经够了  但是如果用long接收超过的概率太大了  我一开始没留意  直接用Long类型的随机数生成器生成的值基本上很容易超出腾讯云的范围

**Comment by yanglbme** [comment]
这里我们考虑过，目前腾讯云对于超出范围的 msgRandom，会给出如下的报错：

```json
SendMsgResult{msgTime=null, msgKey='null', actionStatus='FAIL', errorInfo='Invalid format of MsgRandom', errorCode=90005}
```

如果 sdk 来校验，无非也是抛出异常提示。所以我们决定由开发者自己来控制就好了。
