### ISSUE TITLE
获取群组详细资料接口群基础资料字段缺失

### ISSUE THREAD

**Issue by yinliang0739** [doocs/qcloud-im-server-sdk-java#94]
获取群组详细资料接口群基础资料字段缺失，与api文档对应有欠缺，比如当前群员数量MemberNum，最大成员数量MaxMemberNum
![image](https://user-images.githubusercontent.com/34122429/152949159-96cb97d8-5d55-4b0b-b919-b50006de2e97.png)

**Comment by yanglbme** [comment]
已收到，今天晚点我们查一下哈

**Comment by yanglbme** [comment]
谢谢反馈，v0.3.11 版本已修复。

**Comment by yanglbme** [comment]
已修复，需要再升个小版本
